### PR TITLE
[#182563382] - Change e2e container to not run as root

### PR DESCRIPTION
**Pull request by dna-minn**

### CODE REVIEW

**Review by mbarkley — COMMENTED** [review]
LGTM, but let's get a +1 from someone on the workbench team before we merge.

@mpanik for context, we're standardizing/simplifying the e2e test setup across all microservices, including an important security fix (not running as root). @dna-minn had to move all files from `src/main/java` to `src/test/java` to get it working properly.

**Review by sharvari-kapadia — APPROVED** [review]
+1 on Max's comment, otherwise the PR LGTM!

**Review by mpanik — APPROVED** [review]
Looks great! This is indeed a really nice clean up and simplification.

**Review by mbarkley — APPROVED** [review]
LGTM

**Pull request merged**
